import { Router } from "express";
import authRoutes from "../modules/auth/auth.routes.js";
import orgRoutes from "../modules/organization/organization.routes.js";
import schoolRoutes from "../modules/school/school.routes.js";
import attendanceRoutes from "../modules/attendance/attendance.routes.js";
import academicRoutes from "../modules/academic/academic.routes.js";
import studentRoutes from "../modules/student/student.routes.js";
import admissionRoutes from "../modules/admission/admission.routes.js";
import feeRoutes from "../modules/fee/fee.routes.js";
import homeworkRoutes from "../modules/homework/homework.routes.js";
import examRoutes from "../modules/exam/exam.routes.js";
import conductRoutes from "../modules/conduct/conduct.routes.js";
import circularRoutes from "../modules/circular/circular.routes.js";
import ptmRoutes from "../modules/ptm/ptm.routes.js";
import timetableRoutes from "../modules/timetable/timetable.routes.js";
import activityRoutes from "../modules/activity/activity.routes.js";
import notificationRoutes from "../modules/notification/notification.routes.js";
import promotionRoutes from "../modules/promotion/promotion.routes.js";
import moderationRoutes from "../modules/moderation/moderation.routes.js";
import auditRoutes from "../modules/audit/audit.routes.js";
import leaveRoutes from "../modules/leave/leave.routes.js";
import teachingAssignmentRoutes from "../modules/teachingAssignment/teachingAssignment.routes.js";
import portalRoutes from "../modules/portal/portal.routes.js";
import smtpSettingsRoutes from "../modules/smtpSettings/smtpSettings.routes.js";
import storageSettingsRoutes from "../modules/storageSettings/storageSettings.routes.js";
import staffLeaveRoutes from "../modules/staffLeave/staffLeave.routes.js";
import staffAttendanceRoutes from "../modules/staffAttendance/staffAttendance.routes.js";
import documentsRoutes from "../modules/documents/documents.routes.js";
import studyMaterialRoutes from "../modules/studyMaterial/studyMaterial.routes.js";

const router = Router();

router.use("/auth", authRoutes);
router.use("/organizations", orgRoutes);
router.use("/schools", schoolRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/academic", academicRoutes);
router.use("/students", studentRoutes);
router.use("/admissions", admissionRoutes);
router.use("/fees", feeRoutes);
router.use("/homework", homeworkRoutes);
router.use("/exams", examRoutes);
router.use("/conduct", conductRoutes);
router.use("/circulars", circularRoutes);
router.use("/ptm", ptmRoutes);
router.use("/timetable", timetableRoutes);
router.use("/activities", activityRoutes);
router.use("/notifications", notificationRoutes);
router.use("/promotions", promotionRoutes);
router.use("/moderation", moderationRoutes);
router.use("/audit-logs", auditRoutes);
router.use("/leave", leaveRoutes);
router.use("/teaching-assignments", teachingAssignmentRoutes);
router.use("/portal", portalRoutes);
router.use("/smtp", smtpSettingsRoutes);
router.use("/storage", storageSettingsRoutes);
router.use("/staff-leave", staffLeaveRoutes);
router.use("/staff-attendance", staffAttendanceRoutes);
router.use("/documents", documentsRoutes);
router.use("/study-material", studyMaterialRoutes);

export default router;
